# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Plugins
gems: [jekyll-paginate]

# Site settings

title: Libriotech
email: post@libriotech.no
description: > # this means to ignore newlines until "baseurl:"
  Libriotech leverer tjenester knyttet til fri programvare for bibliotek, med
  hovedvekt på det frie biblioteksystemet Koha.
url: "https://libriotech.no" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:year/:month/:day/:title.html"
twitter_username: libriotech
github_username:  libriotech
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings

markdown: kramdown
